import { v4 as uuidv4 } from 'uuid'
export function generateStaticData():Promise<any[]> {
  let result: any[] = []
  let obj = {
    auart: '',
    aufnr: '',
    aufnt: '',
    aufpl: '',
    autyp: '00',
    barcode: '1234',
    bsart: '',
    budat: '0000-00-00',
    bukrs: '',
    batchID: '0305950-339',
    bwart: '',
    cardmame: '',
    cardmo: '',
    cardname: '',
    cardno: '',
    carnumber: '',
    carnumbert: '',
    cartno: '0',
    charg: '',
    chart: '',
    checkqty: '0.000',
    cpudt: '0000-00-00',
    cputm: '00:00:00',
    dabmg: '0.000',
    delivnum: '',
    ebeln: '',
    ebelp: '00000',
    eindt: '0000-00-00',
    erfme: 'PCS',
    erfmg: '2.000',
    etens: '0000',
    grtxt: '',
    grund: '0000',
    hsdat: '0000-00-00',
    idnrk: '',
    idttm: '',
    insme: '0.000',
    insmk: '',
    kdauf: '',
    kdpos: '000000',
    kostl: 'CE010500',
    ktext: '工程中心机器人技术部',
    kunnr: '',
    labst: '0.000',
    lfart: '',
    lfsta: '',
    lfstat: '',
    lgort: '5901',
    lgotm: '',
    lgott: '',
    licha: '',
    lifnr: '',
    lined: '',
    maktx: '白色衬衫^定制^男^L',
    materialDesc: '白色衬衫^定制^男^L',
    matkl: '',
    matnr: '000000500000003986',
    materialID: '000000500000003986',
    mblnr: '',
    meins: '',
    menge: '0.000',
    minmenge: '0.000',
    mjahr: '0000',
    mtart: '',
    namE1: '',
    ngeln: '',
    ngelnt: '',
    objnr: '',
    oclas: '',
    operator: '',
    posnr: '00000',
    posnv: '000000',
    prilv: '',
    prodbatch: '',
    prodbatct: '',
    proje: '',
    prtmg: '0.000',
    qcqty: '0.000',
    quantity: 1,
    reqno: 'K23021400002',
    retext: '18486-范峻池',
    rspos: '0001',
    scrqty: '0.000',
    sgtxT1: '',
    sgtxT2: '',
    sgtxT3: '',
    sgtxT4: '',
    sgtxT5: '',
    sgtxt: '',
    shkzg: '',
    shkzgt: '',
    sjpno: '',
    sobkz: '',
    sortl: '',
    stokz: '',
    stationID: '000303000505050',
    tcqty: '0.000',
    telpo: '',
    txZ01: '',
    umdoex: '',
    umidr: '',
    umlme: '0.000',
    ummat: '',
    umprj: '',
    umran: '',
    umsmk: '',
    umspj: '',
    usnam: '',
    vbelv: '',
    veran: '',
    vfdat: '0000-00-00',
    vgbel: '',
    vgpos: '000000',
    vstel: '',
    wemng: '0.000',
    werks: '2288',
    werkt: '',
    wmS_AREA: '',
    wmS_AREA_T: '',
    wmS_LGORT: '',
    wmS_LGORT_T: '',
    wmS_TOOLS: '',
    wmS_TOOLS_T: '',
    workp: '',
    workt: '',
    xblnr: '',
    xchpf: '',
    zeile: '0000',
    zzdoex: '',
    zzpj: ''
  }
  for (let i = 0; i < 3; i++) {
    // 就变化其中几个参数
    result.push({...obj, barcode: `${obj.barcode}-${i + 1}`, erfmg: `${i + 1}`, operator: `机器人${i + 1}`, uuid: uuidv4()})
  }

  return new Promise(resolve => {
    setTimeout(() => {
      resolve(result)
    }, 1500)
  })
}

